name: Ubuntu

on:
  push:
    branches: [ main, sdl ]
    
  pull_request:
    branches: [ main, sdl ]
    
jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#   To run cmake later
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.16.x'

    - name: update apt
      run: sudo apt-get update

    - name: install raylib dependencies
      run: sudo apt install libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev

    - name: make setup
      run: make setup

    - name: make bin/app
      run: make bin/app

    - name: 'export binary'
      uses: actions/upload-artifact@v4
      with:
          name: app
          path: bin/app

    - name: make clean
      run: make clean

    - name: make compileLib
      run: make compileLib

    - name: make clean
      run: make clean
      
    - name: make bin/app CXX=g++
      run: make bin/app CXX=g++
    
    - name: make clean
      run: make clean
