name: Windows

on:
  push:
    branches: [ main, sdl ]
    
  pull_request:
    branches: [ main, sdl ]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
#   To run cmake later
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.16.x'
      
    - name: make setup
      run: mingw32-make setup
      shell: cmd
      
    - name: make bin/app
      run: mingw32-make bin/app
      shell: cmd
      
    - name: export binary
      uses: actions/upload-artifact@v4
      with:
          name: app.exe
          path: bin/app.exe
      
    - name: make clean
      run: mingw32-make clean
      shell: cmd

    - name: make compileLib
      run: mingw32-make compileLib
      shell: cmd

    - name: make clean
      run: mingw32-make clean
      shell: cmd

    - name: make bin/app CXX=g++
      run: mingw32-make bin/app CXX=g++
      shell: cmd
  
    - name: make clean
      run: mingw32-make clean
      shell: cmd
